# Makefile for the Chapter 9 Stage 3 myfirst driver.
#
# A first-in / first-out echo driver: writes append, reads drain.

KMOD=    myfirst
SRCS=    myfirst.c
SRCS+=   device_if.h bus_if.h

.include <bsd.kmod.mk>
