# Lab 1: Reproducing a Log Flood
#
# Builds the user-space flood driver.  The two kernel-module variants
# live in the `unlimited/` and `limited/` subdirectories.

PROG=		flood
SRCS=		flood.c
NO_MAN=		yes
MK_WERROR=	no

.include <bsd.prog.mk>
