# Makefile for myfirst driver
#
# Stage 0 of Chapter 7: minimal scaffold that loads and unloads,
# without registering any device or creating /dev nodes.

KMOD=    myfirst
SRCS=    myfirst.c

.include <bsd.kmod.mk>
